### ISSUE TITLE
Using as default subchart not working

### ISSUE THREAD

**Issue by dalefrancis88** [camptocamp/helm-geoserver-cloud#109]
Hey,

First of all thanks for creating this, we're hoping it can be usefull for what we're wanting.

I've created the below basic chart, here's the values yaml

```
geoservercloud:
  global:
    profile: standalone,jdbcconfig,datadir,catalog
  geoserver:
    services:
      webui:
        service:
          type: "LoadBalancer"
```

When we go and try to do anything like reload the Configuration and catalog we get the error 'java.lang.NullPointerException: Cannot invoke "org.geoserver.config.GeoServerLoaderProxy.reload()" because "loader" is null' also when we try to connect to the database it's complaining about postgis not being installed. That's less of a problem though because looking at it, it looks focused on just config so we'll likely create an external for our needs

![image](https://user-images.githubusercontent.com/1909325/212416215-6a41dd92-9f11-4933-9233-20d115777a05.png)
