### ISSUE TITLE
Documentation update request/dependencies problem

### ISSUE THREAD

**Issue by azk1el** [camptocamp/helm-geoserver-cloud#158]
Hi, I am trying to deploy it on AKS via argo using Helm, and I occur this problem that it awaits for database(there is no value regarding database in values.yaml or possibility to add external endpoint for azure postgres instance). 

![Screenshot 2023-12-21 at 11 26 49](https://github.com/camptocamp/helm-geoserver-cloud/assets/65564221/fbb6903d-2ce8-4f8d-8de8-ce80f6db6212)

In the other configuration with datadir it returns java error 
![Screenshot 2023-12-21 at 11 00 41](https://github.com/camptocamp/helm-geoserver-cloud/assets/65564221/b3ed9d89-6d11-48de-bede-c9ac43a40eff)

(Rabbit mq is added as a dependency running in the same namespace)

```
apiVersion: v2
dependencies:
 - alias: geoserver
   name: custom-pod
   repository: https://camptocamp.github.io/helm-custom-pod/
   version: 0.6.2
 - name: 'rabbitmq'
   version: 11.3.0
   repository: 'https://charts.bitnami.com/bitnami'
   condition: rabbitmq.enabled
# - name: common
#   repository: https://camptocamp.github.io/helm-common
#   version: 0.7.2
 - name: postgresql
   version: 13.2.24
   repository: https://charts.bitnami.com/bitnami
   condition: postgresql.enabled
 - name: geoservercloud
   repository: https://camptocamp.github.io/helm-geoserver-cloud
   version: 0.6.2
description: A Helm chart for Geoserver-cloud
name: geoservercloud
version: 0.6.4
``` 

In both cases it looks like it cannot get a configfile from weird urls.

(I have used many variations with dependencies adding rabbitmq,postgres,custom-pod, and can not make it running. Idea behind helm should be that it contains all the dependencies. Can we get more detailed documentation for deployment on kubernetes cluster or add all necessary dependencies in to the chart?

Best regards

**Comment by amoscatelli** [comment]
I keep on having errors about resolving : 
http://config:8080

I can't find a fully working "hello world" example ...

:[

**Comment by azk1el** [comment]
> I keep on having errors about resolving : http://config:8080
> 
> I can't find a fully working "hello world" example ...
> 
> :[

From my research you have to edit value as comment say in chart

```
env: &common-env
  GEOSERVER_BASE_PATH:
    # NB: do not put a trailing '/' character
    value: '/geoserver-cloud'
  SPRING_PROFILES_ACTIVE:
    # this must be explicitly overridden with either
    # "standalone,jdbcconfig,kube" or "standalone,datadir,kube"
    value: not-set
``` 

The problem occurs further when you choose values (had additional dependency for rabbitmq). And there will be java spring framework errors with "standalone,datadir,kube" configuration

OR

There will be database connection issue with "standalone,jdbcconfig,kube". Because it is looked to database named database that should contain config as far as I understand but there is no such thing in helm chart.
