### ISSUE TITLE
releaseTrunc value is no longer accepted at root level

### ISSUE THREAD

**Issue by AlexGacon** [camptocamp/helm-geoserver-cloud#239]
Hello. I am trying to update nexsis deployment to helm chart 2.1.2 (from 0.9.1) and I have regressions:

The releaseTrunc value below the geoserver: entry is no longer accepted. If I remove it, I have ConfigMap conflicts between different environments

The affinity part of the deployment is going wrong. In debug mode, I end up with something like:
```
      nodeSelector:
        node.kubernetes.io/role: sigaffinity:
        podAntiAffinity:
```
My inputs are:
```
-- default values.yaml
  additional-stuff: &additional-stuff
    releaseTrunc: 60
    nodeSelector:
      node.kubernetes.io/role: sig

```
and
```
-- generated for a given environment
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - geoserver
                  topologyKey: failure-domain.beta.kubernetes.io/zone
                weight: 100
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - geoserver
                  topologyKey: kubernetes.io/hostname
                weight: 99
```
