### ISSUE TITLE
metadata customization is not working

### ISSUE THREAD

**Issue by AlexGacon** [camptocamp/helm-geoserver-cloud#244]
I try to change some parameters of the metadata block but there are not taken into account:
```
geoservercloud:
  global: *global


  additional-stuff: &additional-stuff
    releaseTrunc: 60
    nodeSelector:
      node.kubernetes.io/role: sig
  geoserver:

    metadata:
      enabled: false
```
I still have a metadata configmap generated. If I try to change the releaseTrunc parameter, it is not taken into account too.
