### ISSUE TITLE
Add example or documentation on volume sharing between pods

### ISSUE THREAD

**Issue by jorgejesus** [camptocamp/helm-geoserver-cloud#287]
On the current  deployment examples we need an extra folder for raster/vector data sharing between pods in a k8s, that for examples will be read both by the webgui and/or wms pods

For example on https://github.com/camptocamp/helm-geoserver-cloud/blob/9d1b0337b4a9a59f2bef297605f58ed155af65b0/examples/pgconfig-wms-hpa/values.yaml#L10

Something like this to add another volume share:

```yaml
additionalVolumes: &additional-volumes
  cache:
    emptyDir: {}
  shared-data-gs:
    persistentVolumeClaim:
        claimName: shared-data-gs


additionalVolumeMounts: &additional-volume-mounts
  /mnt/gs-share:
    name: 'shared-data-gs'
  /mnt/cache:
    name: 'cache'
```

And a PVC like this: 

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-gs
  namespace: geoserver-cloud-2-26
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
# change storageClassName to what you have available on your k8s
  storageClassName: "do-block-storage"
```

This could just be on the README.md  as example
