### ISSUE TITLE
Struggling to connect Geoserver-Cloud to a remote Db

### ISSUE THREAD

**Issue by AJMcKane** [camptocamp/helm-geoserver-cloud#79]
Hi there, 

I'm investigating migrating from geoserver to geoserver-cloud for stability & customisation reasons, and am currently trying to test using the helm-geoserver-cloud. 

The docs list the below values as how to configure for an external config db:

<html>
<body>

geoserver.jdbc.external | bool | false |  
-- | -- | -- | --
geoserver.jdbc.postgresqlDatabase.secretKey | string | "" |  
geoserver.jdbc.postgresqlDatabase.secretName | string | "" |  
geoserver.jdbc.postgresqlDatabase.value | string | "" |  
geoserver.jdbc.postgresqlHostName.secretKey | string | "" |  
geoserver.jdbc.postgresqlHostName.secretName | string | "" |  
geoserver.jdbc.postgresqlHostName.value | string | "" |  
geoserver.jdbc.postgresqlPassword.secretKey | string | "" |  
geoserver.jdbc.postgresqlPassword.secretName | string | "" |  
geoserver.jdbc.postgresqlPassword.value | string | "" |  
geoserver.jdbc.postgresqlPort.secretKey | string | "" |  
geoserver.jdbc.postgresqlPort.secretName | string | "" |  
geoserver.jdbc.postgresqlPort.value | string | "" |  
geoserver.jdbc.postgresqlUsername.secretKey | string | "" |  
geoserver.jdbc.postgresqlUsername.secretName | string | "" |  
geoserver.jdbc.postgresqlUsername.value | string | ""

</body>
</html>

But upon populating the relevant .value elements (as well as setting `postgresql.enabled : false`)  I can see from the logs of the web-gui container that these settings are not being used.  When I dug into the repo I can see that the template file is actually expecting a [.configVariables array](https://github.com/camptocamp/helm-geoserver-cloud/blob/master/templates/_helpers.tpl#L127), with the same KVP's as what is hardcoded for an internal postgres server. 

```
geoservercloud:
  geoserver:
    jdbc:
      external: true
      configVariables:
        - name: "JDBCCONFIG_DATABASE"
          value: "geoserver_cloud_config" 
        - name: "JDBCCONFIG_HOST"
          value: "TEST_HOST"
        - name: "JDBCCONFIG_USERNAME"
          value: "TEST_USER"
        - name: "JDBCCONFIG_PASSWORD"
          value: "SOME_PASSWORD"
        - name: "JDBCCONFIG_PORT"
          value: "5432"
```

I'm now debugging through further issues, but wanted to know if this is expected behaviour?

**Comment by danduk82** [comment]
Hello @AJMcKane , this seems to be correct. 
Do you change something in the `geoservercloud.global.profile` section? It should be `standalone,jdbcconfig` . You might add the `debug` profile to add more logs such as `profile: standalone,jdbcconfig,debug`

Not sure what your problem is, but you might want to add a bit of error logs here for more context.

Bests

**Comment by AJMcKane** [comment]
Hi @danduk82, 

I'll switch the profiles over and see if I can get anymore detailed logs.  However my problem is that the Helm variables on the Readme for setting up a remote database don't appear to actually function correctly, instead I've had to override a configVariables object that I found by digging into the repo? 

Could you please advise me as to which settings need to be configured in order to connect to a remote DB? Is there an example config? 

Best

**Comment by danduk82** [comment]
@AJMcKane  so you mean that setting something like this does not work?
```yaml
  jdbc:
    external: true
    postgresqlDatabase:
      value: "configdb"
    postgresqlUsername:
      value: ""
      secretKey: "username"
    postgresqlPassword:
      value: ""
      secretKey: "password"
    postgresqlHostName:
      value: ""
      secretKey: "hostname"
    postgresqlPort:
      value: ""
      secretKey: "port"
```

**Comment by danduk82** [comment]
aha, you know what, this is quite wrong in the value files, it should be something like:
```yaml
    jdbc:
      external: true
      configVariables:
        postgresqlDatabase:
          name: "JDBCCONFIG_DATABASE"
          value: "dbname"
        postgresqlUsername:
          name: "JDBCCONFIG_USERNAME"
          value: ""
          secretName: "gscloud-database"
          secretKey: "username"
        postgresqlPassword:
          name: "JDBCCONFIG_PASSWORD"
          value: ""
          secretName: "gscloud-database"
          secretKey: "password"
        postgresqlHostName:
          name: "JDBCCONFIG_HOST"
          value: ""
          secretName: "gscloud-database"
          secretKey: "hostname"
        postgresqlSchema:
          name: "JDBCCONFIG_SCHEMA"
          value: "testing"
```
